#ifndef COMMANDS_H
#define COMMANDS_H

/* COMMANDS FROM CONTROL SYSTEM */

#define RUN_COMMAND  0x01
#define HOME_COMMAND  0x02
#define ABORT_COMMAND 0x03
#define PAUSE_COMMAND 0x04
#define RESUME_COMMAND 0x05
#define ECHO_COMMAND 0x09

/* COMMANDS FROM DRIVER TO CONTROL SYSTEM */

#define TOP_SPEED_REACHED 0xff
#define STEPPERS_STOPPED 0xaa
#define STEPPERS_STARTING 0xbb
#define CLINOSTAT_CONNECTED 0x01

#endif